// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aEZR2R5iRbTAH71yA14j4D
// Component: KvvMsTufGwzW

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import TextInput from "../../TextInput"; // plasmic-import: 1dfWj3ktJsL/component
import Button from "../../Button"; // plasmic-import: jjOKPcyq7uK/component
import { DataFetcher } from "@plasmicpkgs/plasmic-query";
import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import { LottieWrapper } from "@plasmicpkgs/lottie-react";

import { useScreenVariants as useScreenVariantsbss409WXlfZw } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: _BSS409WXlfZw/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: aEZR2R5iRbTAH71yA14j4D/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: KvvMsTufGwzW/css

import SearchsvgIcon from "./icons/PlasmicIcon__Searchsvg"; // plasmic-import: gecQgD2QCTw/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: eFoT8P7C4dm/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: Y7gWLLJRkZ1/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  section?: Flex__<"section">;
  h1?: Flex__<"h1">;
  textInput?: Flex__<typeof TextInput>;
  button?: Flex__<typeof Button>;
  openAiCall?: Flex__<typeof DataFetcher>;
  reveal?: Flex__<typeof Reveal>;
  lottie?: Flex__<typeof LottieWrapper>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "textInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "queryIngredients",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "openAIoutput",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ``
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsbss409WXlfZw()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicHomepage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicHomepage.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicHomepage.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicHomepage.pageMetadata.description}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Stack__
            as={"section"}
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            hasGap={true}
            className={classNames(projectcss.all, sty.section)}
          >
            <h1
              data-plasmic-name={"h1"}
              data-plasmic-override={overrides.h1}
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1
              )}
            >
              {"What Can I Make With..."}
            </h1>
            <div className={classNames(projectcss.all, sty.freeBox__zZTv1)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xOjFi
                )}
              >
                <React.Fragment>
                  <React.Fragment>
                    {
                      "Enter the ingredients you have, and we'll give you some options to cook. \n"
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontStyle: "italic" }}
                  >
                    {"e.g. tomatoes, pasta, bacon"}
                  </span>
                </React.Fragment>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rnjVh
                )}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return $state.openAIoutput;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "Enter the ingredients you have, and we'll give you some options to cook. ";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__uTkI)}>
                <TextInput
                  data-plasmic-name={"textInput"}
                  data-plasmic-override={overrides.textInput}
                  className={classNames("__wab_instance", sty.textInput)}
                  name={"promptInput"}
                  onChange={(...eventArgs) => {
                    generateStateOnChangeProp($state, ["textInput", "value"])(
                      (e => e.target?.value).apply(null, eventArgs)
                    );
                  }}
                  placeholder={"ingredients"}
                  value={
                    generateStateValueProp($state, ["textInput", "value"]) ?? ""
                  }
                />

                <Button
                  data-plasmic-name={"button"}
                  data-plasmic-override={overrides.button}
                  className={classNames("__wab_instance", sty.button)}
                  onClick={async event => {
                    const $steps = {};

                    $steps["setVariable"] = true
                      ? (() => {
                          const actionArgs = {
                            operation: 0,
                            variable: {
                              objRoot: $state,
                              variablePath: ["queryIngredients"]
                            },
                            value: $state.textInput.value
                          };
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;

                            $stateSet(objRoot, variablePath, value);
                            return value;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["setVariable"] != null &&
                      typeof $steps["setVariable"] === "object" &&
                      typeof $steps["setVariable"].then === "function"
                    ) {
                      $steps["setVariable"] = await $steps["setVariable"];
                    }
                  }}
                  submitsForm={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__x47Uw
                    )}
                  >
                    {"Submit"}
                  </div>
                </Button>
              </div>
            </div>
            {(
              hasVariant(globalVariants, "screen", "mobileOnly")
                ? (() => {
                    try {
                      return $state.queryIngredients;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return true;
                      }
                      throw e;
                    }
                  })()
                : (() => {
                    try {
                      return $state.queryIngredients;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return true;
                      }
                      throw e;
                    }
                  })()
            ) ? (
              <DataFetcher
                data-plasmic-name={"openAiCall"}
                data-plasmic-override={overrides.openAiCall}
                body={(() => {
                  try {
                    return {
                      model: "gpt-3.5-turbo",
                      messages: [
                        {
                          role: "system",
                          content: "You are a helpful assistant."
                        },
                        {
                          role: "user",
                          content:
                            "I'm hungry and want ideas of what I can cook. I only have a few ingredients though.The ingredients are;" +
                            $state.queryIngredients +
                            ". Are all my ingredients real food items? If they aren't, explain that you only recommend cooking with real food items and do not continue. If the are real food items, recommend 3 dishes I could cook.Each recommendation should have a title, a description which sells to me why I should make the dish and finally, a estimated duration for cooking the dish.  Respond in html format. The title should be bold and a h2 tage, the description should be in a separate paragraph and the the duration should be a separate paragraph also. Each suggestion on the list should have a space between them."
                        }
                      ]
                    };
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return undefined;
                    }
                    throw e;
                  }
                })()}
                className={classNames("__wab_instance", sty.openAiCall)}
                dataName={"openAIResponse"}
                errorDisplay={
                  <DataCtxReader__>
                    {$ctx => (
                      <React.Fragment>
                        {(() => {
                          try {
                            return undefined;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "Error fetching data";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    )}
                  </DataCtxReader__>
                }
                errorName={"fetchError"}
                headers={{
                  "Content-Type": "application/json",
                  Accept: "application/json",
                  Authorization:
                    "Bearer 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"
                }}
                loadingDisplay={
                  <DataCtxReader__>
                    {$ctx => (
                      <LottieWrapper
                        data-plasmic-name={"lottie"}
                        data-plasmic-override={overrides.lottie}
                        animationData={{
                          v: "4.8.0",
                          meta: {
                            g: "LottieFiles AE 3.1.1",
                            a: "",
                            k: "",
                            d: "",
                            tc: ""
                          },
                          fr: 60,
                          ip: 0,
                          op: 240,
                          w: 1000,
                          h: 1000,
                          nm: "Clock",
                          ddd: 0,
                          assets: [
                            {
                              id: "comp_0",
                              layers: [
                                {
                                  ddd: 0,
                                  ind: 1,
                                  ty: 4,
                                  nm: "Shape Layer 8",
                                  parent: 5,
                                  sr: 1,
                                  ks: {
                                    o: { a: 0, k: 100, ix: 11 },
                                    r: { a: 0, k: 90, ix: 10 },
                                    p: { a: 0, k: [0.749, -71.154, 0], ix: 2 },
                                    a: {
                                      a: 0,
                                      k: [-48.969, -314.969, 0],
                                      ix: 1
                                    },
                                    s: { a: 0, k: [100, 39.778, 100], ix: 6 }
                                  },
                                  ao: 0,
                                  shapes: [
                                    {
                                      ty: "gr",
                                      it: [
                                        {
                                          ty: "rc",
                                          d: 1,
                                          s: { a: 0, k: [32, 225], ix: 2 },
                                          p: { a: 0, k: [0, 0], ix: 3 },
                                          r: { a: 0, k: 30, ix: 4 },
                                          nm: "Rectangle Path 1",
                                          mn: "ADBE Vector Shape - Rect",
                                          hd: false
                                        },
                                        {
                                          ty: "fl",
                                          c: {
                                            a: 0,
                                            k: [
                                              1, 0.549019607843, 0.294117647059,
                                              1
                                            ],
                                            ix: 4
                                          },
                                          o: { a: 0, k: 100, ix: 5 },
                                          r: 1,
                                          bm: 0,
                                          nm: "Fill 1",
                                          mn: "ADBE Vector Graphic - Fill",
                                          hd: false
                                        },
                                        {
                                          ty: "tr",
                                          p: {
                                            a: 0,
                                            k: [-48.969, -314.969],
                                            ix: 2
                                          },
                                          a: { a: 0, k: [0, 0], ix: 1 },
                                          s: { a: 0, k: [100, 100], ix: 3 },
                                          r: { a: 0, k: 0, ix: 6 },
                                          o: { a: 0, k: 100, ix: 7 },
                                          sk: { a: 0, k: 0, ix: 4 },
                                          sa: { a: 0, k: 0, ix: 5 },
                                          nm: "Transform"
                                        }
                                      ],
                                      nm: "Rectangle 1",
                                      np: 3,
                                      cix: 2,
                                      bm: 0,
                                      ix: 1,
                                      mn: "ADBE Vector Group",
                                      hd: false
                                    }
                                  ],
                                  ip: 0,
                                  op: 240,
                                  st: 0,
                                  bm: 0
                                },
                                {
                                  ddd: 0,
                                  ind: 2,
                                  ty: 4,
                                  nm: "Shape Layer 7",
                                  parent: 5,
                                  sr: 1,
                                  ks: {
                                    o: { a: 0, k: 100, ix: 11 },
                                    r: { a: 0, k: 0, ix: 10 },
                                    p: { a: 0, k: [30.947, -65.969, 0], ix: 2 },
                                    a: {
                                      a: 0,
                                      k: [-48.969, -211.969, 0],
                                      ix: 1
                                    },
                                    s: { a: 0, k: [100, 100, 100], ix: 6 }
                                  },
                                  ao: 0,
                                  shapes: [
                                    {
                                      ty: "gr",
                                      it: [
                                        {
                                          ty: "rc",
                                          d: 1,
                                          s: { a: 0, k: [24, 225], ix: 2 },
                                          p: { a: 0, k: [0, 0], ix: 3 },
                                          r: { a: 0, k: 30, ix: 4 },
                                          nm: "Rectangle Path 1",
                                          mn: "ADBE Vector Shape - Rect",
                                          hd: false
                                        },
                                        {
                                          ty: "fl",
                                          c: {
                                            a: 0,
                                            k: [
                                              1, 0.549019607843, 0.294117647059,
                                              1
                                            ],
                                            ix: 4
                                          },
                                          o: { a: 0, k: 100, ix: 5 },
                                          r: 1,
                                          bm: 0,
                                          nm: "Fill 1",
                                          mn: "ADBE Vector Graphic - Fill",
                                          hd: false
                                        },
                                        {
                                          ty: "tr",
                                          p: {
                                            a: 0,
                                            k: [-53.969, -314.969],
                                            ix: 2
                                          },
                                          a: { a: 0, k: [0, 0], ix: 1 },
                                          s: { a: 0, k: [100, 100], ix: 3 },
                                          r: { a: 0, k: 0, ix: 6 },
                                          o: { a: 0, k: 100, ix: 7 },
                                          sk: { a: 0, k: 0, ix: 4 },
                                          sa: { a: 0, k: 0, ix: 5 },
                                          nm: "Transform"
                                        }
                                      ],
                                      nm: "Rectangle 1",
                                      np: 3,
                                      cix: 2,
                                      bm: 0,
                                      ix: 1,
                                      mn: "ADBE Vector Group",
                                      hd: false
                                    }
                                  ],
                                  ip: 0,
                                  op: 240,
                                  st: 0,
                                  bm: 0
                                },
                                {
                                  ddd: 0,
                                  ind: 3,
                                  ty: 4,
                                  nm: "Shape Layer 6",
                                  parent: 5,
                                  sr: 1,
                                  ks: {
                                    o: { a: 0, k: 100, ix: 11 },
                                    r: { a: 0, k: 0, ix: 10 },
                                    p: {
                                      a: 0,
                                      k: [-27.387, -65.969, 0],
                                      ix: 2
                                    },
                                    a: {
                                      a: 0,
                                      k: [-48.969, -211.969, 0],
                                      ix: 1
                                    },
                                    s: { a: 0, k: [100, 100, 100], ix: 6 }
                                  },
                                  ao: 0,
                                  shapes: [
                                    {
                                      ty: "gr",
                                      it: [
                                        {
                                          ty: "rc",
                                          d: 1,
                                          s: { a: 0, k: [24, 225], ix: 2 },
                                          p: { a: 0, k: [0, 0], ix: 3 },
                                          r: { a: 0, k: 30, ix: 4 },
                                          nm: "Rectangle Path 1",
                                          mn: "ADBE Vector Shape - Rect",
                                          hd: false
                                        },
                                        {
                                          ty: "fl",
                                          c: {
                                            a: 0,
                                            k: [
                                              1, 0.549019607843, 0.294117647059,
                                              1
                                            ],
                                            ix: 4
                                          },
                                          o: { a: 0, k: 100, ix: 5 },
                                          r: 1,
                                          bm: 0,
                                          nm: "Fill 1",
                                          mn: "ADBE Vector Graphic - Fill",
                                          hd: false
                                        },
                                        {
                                          ty: "tr",
                                          p: {
                                            a: 0,
                                            k: [-43.969, -314.969],
                                            ix: 2
                                          },
                                          a: { a: 0, k: [0, 0], ix: 1 },
                                          s: { a: 0, k: [100, 100], ix: 3 },
                                          r: { a: 0, k: 0, ix: 6 },
                                          o: { a: 0, k: 100, ix: 7 },
                                          sk: { a: 0, k: 0, ix: 4 },
                                          sa: { a: 0, k: 0, ix: 5 },
                                          nm: "Transform"
                                        }
                                      ],
                                      nm: "Rectangle 1",
                                      np: 3,
                                      cix: 2,
                                      bm: 0,
                                      ix: 1,
                                      mn: "ADBE Vector Group",
                                      hd: false
                                    }
                                  ],
                                  ip: 0,
                                  op: 240,
                                  st: 0,
                                  bm: 0
                                },
                                {
                                  ddd: 0,
                                  ind: 4,
                                  ty: 4,
                                  nm: "Shape Layer 10",
                                  parent: 5,
                                  sr: 1,
                                  ks: {
                                    o: { a: 0, k: 100, ix: 11 },
                                    r: { a: 0, k: 0, ix: 10 },
                                    p: { a: 0, k: [1.78, 70.488, 0], ix: 2 },
                                    a: { a: 0, k: [1.78, -66.969, 0], ix: 1 },
                                    s: { a: 0, k: [81.679, 87.617, 100], ix: 6 }
                                  },
                                  ao: 0,
                                  shapes: [
                                    {
                                      ty: "gr",
                                      it: [
                                        {
                                          ty: "rc",
                                          d: 1,
                                          s: { a: 0, k: [184, 10], ix: 2 },
                                          p: { a: 0, k: [0, 0], ix: 3 },
                                          r: { a: 0, k: 100, ix: 4 },
                                          nm: "Rectangle Path 1",
                                          mn: "ADBE Vector Shape - Rect",
                                          hd: false
                                        },
                                        {
                                          ty: "fl",
                                          c: {
                                            a: 0,
                                            k: [
                                              1, 0.549019607843, 0.294117647059,
                                              1
                                            ],
                                            ix: 4
                                          },
                                          o: { a: 0, k: 100, ix: 5 },
                                          r: 1,
                                          bm: 0,
                                          nm: "Fill 1",
                                          mn: "ADBE Vector Graphic - Fill",
                                          hd: false
                                        },
                                        {
                                          ty: "tr",
                                          p: {
                                            a: 0,
                                            k: [0.749, -304.106],
                                            ix: 2
                                          },
                                          a: { a: 0, k: [0, 0], ix: 1 },
                                          s: { a: 0, k: [100, 100], ix: 3 },
                                          r: { a: 0, k: 0, ix: 6 },
                                          o: { a: 0, k: 100, ix: 7 },
                                          sk: { a: 0, k: 0, ix: 4 },
                                          sa: { a: 0, k: 0, ix: 5 },
                                          nm: "Transform"
                                        }
                                      ],
                                      nm: "Rectangle 2",
                                      np: 3,
                                      cix: 2,
                                      bm: 0,
                                      ix: 1,
                                      mn: "ADBE Vector Group",
                                      hd: false
                                    },
                                    {
                                      ty: "gr",
                                      it: [
                                        {
                                          ty: "rc",
                                          d: 1,
                                          s: { a: 0, k: [180, 67], ix: 2 },
                                          p: { a: 0, k: [0, 0], ix: 3 },
                                          r: { a: 0, k: 100, ix: 4 },
                                          nm: "Rectangle Path 1",
                                          mn: "ADBE Vector Shape - Rect",
                                          hd: false
                                        },
                                        {
                                          ty: "fl",
                                          c: {
                                            a: 0,
                                            k: [
                                              1, 0.549019607843, 0.294117647059,
                                              1
                                            ],
                                            ix: 4
                                          },
                                          o: { a: 0, k: 100, ix: 5 },
                                          r: 1,
                                          bm: 0,
                                          nm: "Fill 1",
                                          mn: "ADBE Vector Graphic - Fill",
                                          hd: false
                                        },
                                        {
                                          ty: "tr",
                                          p: {
                                            a: 0,
                                            k: [0.749, -272.106],
                                            ix: 2
                                          },
                                          a: { a: 0, k: [0, 0], ix: 1 },
                                          s: { a: 0, k: [100, 100], ix: 3 },
                                          r: { a: 0, k: 0, ix: 6 },
                                          o: { a: 0, k: 100, ix: 7 },
                                          sk: { a: 0, k: 0, ix: 4 },
                                          sa: { a: 0, k: 0, ix: 5 },
                                          nm: "Transform"
                                        }
                                      ],
                                      nm: "Rectangle 1",
                                      np: 3,
                                      cix: 2,
                                      bm: 0,
                                      ix: 2,
                                      mn: "ADBE Vector Group",
                                      hd: false
                                    }
                                  ],
                                  ip: 0,
                                  op: 240,
                                  st: 0,
                                  bm: 0
                                },
                                {
                                  ddd: 0,
                                  ind: 5,
                                  ty: 4,
                                  nm: "Shape Layer 5",
                                  parent: 6,
                                  sr: 1,
                                  ks: {
                                    o: { a: 0, k: 100, ix: 11 },
                                    r: { a: 0, k: 0, ix: 10 },
                                    p: { a: 0, k: [1.031, -250.969, 0], ix: 2 },
                                    a: { a: 0, k: [1.78, -66.969, 0], ix: 1 },
                                    s: { a: 0, k: [120, 120, 100], ix: 6 }
                                  },
                                  ao: 0,
                                  shapes: [
                                    {
                                      ty: "gr",
                                      it: [
                                        {
                                          ty: "rc",
                                          d: 1,
                                          s: { a: 0, k: [140, 300], ix: 2 },
                                          p: { a: 0, k: [0, 0], ix: 3 },
                                          r: { a: 0, k: 100, ix: 4 },
                                          nm: "Rectangle Path 1",
                                          mn: "ADBE Vector Shape - Rect",
                                          hd: false
                                        },
                                        {
                                          ty: "tm",
                                          s: { a: 0, k: 2, ix: 1 },
                                          e: { a: 0, k: 69, ix: 2 },
                                          o: { a: 0, k: 0, ix: 3 },
                                          m: 1,
                                          ix: 2,
                                          nm: "Trim Paths 1",
                                          mn: "ADBE Vector Filter - Trim",
                                          hd: false
                                        },
                                        {
                                          ty: "st",
                                          c: {
                                            a: 0,
                                            k: [
                                              1, 0.549019607843, 0.294117647059,
                                              1
                                            ],
                                            ix: 3
                                          },
                                          o: { a: 0, k: 100, ix: 4 },
                                          w: { a: 0, k: 24, ix: 5 },
                                          lc: 2,
                                          lj: 1,
                                          ml: 4,
                                          bm: 0,
                                          nm: "Stroke 1",
                                          mn: "ADBE Vector Graphic - Stroke",
                                          hd: false
                                        },
                                        {
                                          ty: "tr",
                                          p: {
                                            a: 0,
                                            k: [0.749, -203.828],
                                            ix: 2
                                          },
                                          a: { a: 0, k: [0, 0], ix: 1 },
                                          s: { a: 0, k: [100, 100], ix: 3 },
                                          r: { a: 0, k: 0, ix: 6 },
                                          o: { a: 0, k: 100, ix: 7 },
                                          sk: { a: 0, k: 0, ix: 4 },
                                          sa: { a: 0, k: 0, ix: 5 },
                                          nm: "Transform"
                                        }
                                      ],
                                      nm: "Rectangle 1",
                                      np: 4,
                                      cix: 2,
                                      bm: 0,
                                      ix: 1,
                                      mn: "ADBE Vector Group",
                                      hd: false
                                    }
                                  ],
                                  ip: 0,
                                  op: 240,
                                  st: 0,
                                  bm: 0
                                },
                                {
                                  ddd: 0,
                                  ind: 6,
                                  ty: 4,
                                  nm: "Shape Layer 4",
                                  sr: 1,
                                  ks: {
                                    o: { a: 0, k: 100, ix: 11 },
                                    r: { a: 0, k: 0, ix: 10 },
                                    p: { a: 0, k: [500, 640, 0], ix: 2 },
                                    a: { a: 0, k: [0, 0, 0], ix: 1 },
                                    s: { a: 0, k: [100, 100, 100], ix: 6 }
                                  },
                                  ao: 0,
                                  shapes: [
                                    {
                                      ty: "gr",
                                      it: [
                                        {
                                          ty: "rc",
                                          d: 1,
                                          s: { a: 0, k: [64, 465], ix: 2 },
                                          p: { a: 0, k: [0, 0], ix: 3 },
                                          r: { a: 0, k: 30, ix: 4 },
                                          nm: "Rectangle Path 1",
                                          mn: "ADBE Vector Shape - Rect",
                                          hd: false
                                        },
                                        {
                                          ty: "fl",
                                          c: {
                                            a: 0,
                                            k: [
                                              0.760784313725, 0.23137254902,
                                              0.066666666667, 1
                                            ],
                                            ix: 4
                                          },
                                          o: { a: 0, k: 100, ix: 5 },
                                          r: 1,
                                          bm: 0,
                                          nm: "Fill 1",
                                          mn: "ADBE Vector Graphic - Fill",
                                          hd: false
                                        },
                                        {
                                          ty: "tr",
                                          p: {
                                            a: 0,
                                            k: [1.031, 23.031],
                                            ix: 2
                                          },
                                          a: { a: 0, k: [0, 0], ix: 1 },
                                          s: { a: 0, k: [100, 100], ix: 3 },
                                          r: { a: 0, k: 0, ix: 6 },
                                          o: { a: 0, k: 100, ix: 7 },
                                          sk: { a: 0, k: 0, ix: 4 },
                                          sa: { a: 0, k: 0, ix: 5 },
                                          nm: "Transform"
                                        }
                                      ],
                                      nm: "Rectangle 2",
                                      np: 3,
                                      cix: 2,
                                      bm: 0,
                                      ix: 1,
                                      mn: "ADBE Vector Group",
                                      hd: false
                                    },
                                    {
                                      ty: "gr",
                                      it: [
                                        {
                                          ty: "rc",
                                          d: 1,
                                          s: { a: 0, k: [60, 503.401], ix: 2 },
                                          p: { a: 0, k: [0, 0], ix: 3 },
                                          r: { a: 0, k: 30, ix: 4 },
                                          nm: "Rectangle Path 1",
                                          mn: "ADBE Vector Shape - Rect",
                                          hd: false
                                        },
                                        {
                                          ty: "fl",
                                          c: {
                                            a: 0,
                                            k: [
                                              1, 0.549019607843, 0.294117647059,
                                              1
                                            ],
                                            ix: 4
                                          },
                                          o: { a: 0, k: 100, ix: 5 },
                                          r: 1,
                                          bm: 0,
                                          nm: "Fill 1",
                                          mn: "ADBE Vector Graphic - Fill",
                                          hd: false
                                        },
                                        {
                                          ty: "tr",
                                          p: {
                                            a: 0,
                                            k: [-7.969, 1.031],
                                            ix: 2
                                          },
                                          a: { a: 0, k: [0, 0], ix: 1 },
                                          s: { a: 0, k: [68.967, 100], ix: 3 },
                                          r: { a: 0, k: 0, ix: 6 },
                                          o: { a: 0, k: 100, ix: 7 },
                                          sk: { a: 0, k: 0, ix: 4 },
                                          sa: { a: 0, k: 0, ix: 5 },
                                          nm: "Transform"
                                        }
                                      ],
                                      nm: "Rectangle 4",
                                      np: 3,
                                      cix: 2,
                                      bm: 0,
                                      ix: 2,
                                      mn: "ADBE Vector Group",
                                      hd: false
                                    },
                                    {
                                      ty: "gr",
                                      it: [
                                        {
                                          ty: "rc",
                                          d: 1,
                                          s: { a: 0, k: [60, 503.401], ix: 2 },
                                          p: { a: 0, k: [0, 0], ix: 3 },
                                          r: { a: 0, k: 30, ix: 4 },
                                          nm: "Rectangle Path 1",
                                          mn: "ADBE Vector Shape - Rect",
                                          hd: false
                                        },
                                        {
                                          ty: "fl",
                                          c: {
                                            a: 0,
                                            k: [
                                              0.945098039216, 0.478431372549,
                                              0.211764705882, 1
                                            ],
                                            ix: 4
                                          },
                                          o: { a: 0, k: 100, ix: 5 },
                                          r: 1,
                                          bm: 0,
                                          nm: "Fill 1",
                                          mn: "ADBE Vector Graphic - Fill",
                                          hd: false
                                        },
                                        {
                                          ty: "tr",
                                          p: { a: 0, k: [1.031, 1.031], ix: 2 },
                                          a: { a: 0, k: [0, 0], ix: 1 },
                                          s: { a: 0, k: [100, 100], ix: 3 },
                                          r: { a: 0, k: 0, ix: 6 },
                                          o: { a: 0, k: 100, ix: 7 },
                                          sk: { a: 0, k: 0, ix: 4 },
                                          sa: { a: 0, k: 0, ix: 5 },
                                          nm: "Transform"
                                        }
                                      ],
                                      nm: "Rectangle 1",
                                      np: 3,
                                      cix: 2,
                                      bm: 0,
                                      ix: 3,
                                      mn: "ADBE Vector Group",
                                      hd: false
                                    }
                                  ],
                                  ip: 0,
                                  op: 240,
                                  st: 0,
                                  bm: 0
                                }
                              ]
                            },
                            {
                              id: "comp_1",
                              layers: [
                                {
                                  ddd: 0,
                                  ind: 1,
                                  ty: 4,
                                  nm: "Shape Layer 5",
                                  sr: 1,
                                  ks: {
                                    o: { a: 0, k: 100, ix: 11 },
                                    r: { a: 0, k: 0, ix: 10 },
                                    p: {
                                      a: 0,
                                      k: [501.031, 277.053, 0],
                                      ix: 2
                                    },
                                    a: {
                                      a: 0,
                                      k: [-1.591, -134.947, 0],
                                      ix: 1
                                    },
                                    s: { a: 0, k: [124, 129.376, 100], ix: 6 }
                                  },
                                  ao: 0,
                                  shapes: [
                                    {
                                      ty: "gr",
                                      it: [
                                        {
                                          d: 1,
                                          ty: "el",
                                          s: {
                                            a: 0,
                                            k: [174.251, 230.106],
                                            ix: 2
                                          },
                                          p: { a: 0, k: [0, 0], ix: 3 },
                                          nm: "Ellipse Path 1",
                                          mn: "ADBE Vector Shape - Ellipse",
                                          hd: false
                                        },
                                        {
                                          ty: "fl",
                                          c: {
                                            a: 0,
                                            k: [
                                              1, 0.549019607843, 0.294117647059,
                                              1
                                            ],
                                            ix: 4
                                          },
                                          o: { a: 0, k: 100, ix: 5 },
                                          r: 1,
                                          bm: 0,
                                          nm: "Fill 1",
                                          mn: "ADBE Vector Graphic - Fill",
                                          hd: false
                                        },
                                        {
                                          ty: "tr",
                                          p: {
                                            a: 0,
                                            k: [-2.622, -134.947],
                                            ix: 2
                                          },
                                          a: { a: 0, k: [0, 0], ix: 1 },
                                          s: { a: 0, k: [100, 100], ix: 3 },
                                          r: { a: 0, k: 0, ix: 6 },
                                          o: { a: 0, k: 100, ix: 7 },
                                          sk: { a: 0, k: 0, ix: 4 },
                                          sa: { a: 0, k: 0, ix: 5 },
                                          nm: "Transform"
                                        }
                                      ],
                                      nm: "Ellipse 1",
                                      np: 3,
                                      cix: 2,
                                      bm: 0,
                                      ix: 1,
                                      mn: "ADBE Vector Group",
                                      hd: false
                                    }
                                  ],
                                  ip: 0,
                                  op: 240,
                                  st: 0,
                                  bm: 0
                                },
                                {
                                  ddd: 0,
                                  ind: 2,
                                  ty: 4,
                                  nm: "Shape Layer 4",
                                  sr: 1,
                                  ks: {
                                    o: { a: 0, k: 100, ix: 11 },
                                    r: { a: 0, k: 0, ix: 10 },
                                    p: { a: 0, k: [500, 640, 0], ix: 2 },
                                    a: { a: 0, k: [0, 0, 0], ix: 1 },
                                    s: { a: 0, k: [100, 100, 100], ix: 6 }
                                  },
                                  ao: 0,
                                  shapes: [
                                    {
                                      ty: "gr",
                                      it: [
                                        {
                                          ty: "rc",
                                          d: 1,
                                          s: { a: 0, k: [64, 465], ix: 2 },
                                          p: { a: 0, k: [0, 0], ix: 3 },
                                          r: { a: 0, k: 30, ix: 4 },
                                          nm: "Rectangle Path 1",
                                          mn: "ADBE Vector Shape - Rect",
                                          hd: false
                                        },
                                        {
                                          ty: "fl",
                                          c: {
                                            a: 0,
                                            k: [
                                              0.760784313725, 0.23137254902,
                                              0.066666666667, 1
                                            ],
                                            ix: 4
                                          },
                                          o: { a: 0, k: 100, ix: 5 },
                                          r: 1,
                                          bm: 0,
                                          nm: "Fill 1",
                                          mn: "ADBE Vector Graphic - Fill",
                                          hd: false
                                        },
                                        {
                                          ty: "tr",
                                          p: {
                                            a: 0,
                                            k: [1.031, 23.031],
                                            ix: 2
                                          },
                                          a: { a: 0, k: [0, 0], ix: 1 },
                                          s: { a: 0, k: [100, 100], ix: 3 },
                                          r: { a: 0, k: 0, ix: 6 },
                                          o: { a: 0, k: 100, ix: 7 },
                                          sk: { a: 0, k: 0, ix: 4 },
                                          sa: { a: 0, k: 0, ix: 5 },
                                          nm: "Transform"
                                        }
                                      ],
                                      nm: "Rectangle 3",
                                      np: 3,
                                      cix: 2,
                                      bm: 0,
                                      ix: 1,
                                      mn: "ADBE Vector Group",
                                      hd: false
                                    },
                                    {
                                      ty: "gr",
                                      it: [
                                        {
                                          ty: "rc",
                                          d: 1,
                                          s: { a: 0, k: [60, 503.401], ix: 2 },
                                          p: { a: 0, k: [0, 0], ix: 3 },
                                          r: { a: 0, k: 30, ix: 4 },
                                          nm: "Rectangle Path 1",
                                          mn: "ADBE Vector Shape - Rect",
                                          hd: false
                                        },
                                        {
                                          ty: "fl",
                                          c: {
                                            a: 0,
                                            k: [
                                              1, 0.549019607843, 0.294117647059,
                                              1
                                            ],
                                            ix: 4
                                          },
                                          o: { a: 0, k: 100, ix: 5 },
                                          r: 1,
                                          bm: 0,
                                          nm: "Fill 1",
                                          mn: "ADBE Vector Graphic - Fill",
                                          hd: false
                                        },
                                        {
                                          ty: "tr",
                                          p: {
                                            a: 0,
                                            k: [-7.969, 1.031],
                                            ix: 2
                                          },
                                          a: { a: 0, k: [0, 0], ix: 1 },
                                          s: { a: 0, k: [68.967, 100], ix: 3 },
                                          r: { a: 0, k: 0, ix: 6 },
                                          o: { a: 0, k: 100, ix: 7 },
                                          sk: { a: 0, k: 0, ix: 4 },
                                          sa: { a: 0, k: 0, ix: 5 },
                                          nm: "Transform"
                                        }
                                      ],
                                      nm: "Rectangle 4",
                                      np: 3,
                                      cix: 2,
                                      bm: 0,
                                      ix: 2,
                                      mn: "ADBE Vector Group",
                                      hd: false
                                    },
                                    {
                                      ty: "gr",
                                      it: [
                                        {
                                          ty: "rc",
                                          d: 1,
                                          s: { a: 0, k: [60, 503.401], ix: 2 },
                                          p: { a: 0, k: [0, 0], ix: 3 },
                                          r: { a: 0, k: 30, ix: 4 },
                                          nm: "Rectangle Path 1",
                                          mn: "ADBE Vector Shape - Rect",
                                          hd: false
                                        },
                                        {
                                          ty: "fl",
                                          c: {
                                            a: 0,
                                            k: [
                                              0.945098099054, 0.478431402468,
                                              0.211764720842, 1
                                            ],
                                            ix: 4
                                          },
                                          o: { a: 0, k: 100, ix: 5 },
                                          r: 1,
                                          bm: 0,
                                          nm: "Fill 1",
                                          mn: "ADBE Vector Graphic - Fill",
                                          hd: false
                                        },
                                        {
                                          ty: "tr",
                                          p: { a: 0, k: [1.031, 1.031], ix: 2 },
                                          a: { a: 0, k: [0, 0], ix: 1 },
                                          s: { a: 0, k: [100, 100], ix: 3 },
                                          r: { a: 0, k: 0, ix: 6 },
                                          o: { a: 0, k: 100, ix: 7 },
                                          sk: { a: 0, k: 0, ix: 4 },
                                          sa: { a: 0, k: 0, ix: 5 },
                                          nm: "Transform"
                                        }
                                      ],
                                      nm: "Rectangle 1",
                                      np: 3,
                                      cix: 2,
                                      bm: 0,
                                      ix: 3,
                                      mn: "ADBE Vector Group",
                                      hd: false
                                    }
                                  ],
                                  ip: 0,
                                  op: 240,
                                  st: 0,
                                  bm: 0
                                }
                              ]
                            }
                          ],
                          layers: [
                            {
                              ddd: 0,
                              ind: 1,
                              ty: 0,
                              nm: "Fork",
                              parent: 2,
                              refId: "comp_0",
                              sr: 1,
                              ks: {
                                o: { a: 0, k: 100, ix: 11 },
                                r: { a: 0, k: 90, ix: 10 },
                                p: { a: 0, k: [511.049, 580.204, 0], ix: 2 },
                                a: { a: 0, k: [500, 560.63, 0], ix: 1 },
                                s: { a: 0, k: [98, 98, 100], ix: 6 }
                              },
                              ao: 0,
                              w: 1000,
                              h: 1000,
                              ip: 0,
                              op: 240,
                              st: 0,
                              bm: 0
                            },
                            {
                              ddd: 0,
                              ind: 2,
                              ty: 0,
                              nm: "Spoon",
                              refId: "comp_1",
                              sr: 1,
                              ks: {
                                o: { a: 0, k: 100, ix: 11 },
                                r: {
                                  a: 1,
                                  k: [
                                    {
                                      i: { x: [0.833], y: [0.833] },
                                      o: { x: [0.167], y: [0.167] },
                                      t: 0,
                                      s: [-45]
                                    },
                                    { t: 240, s: [315] }
                                  ],
                                  ix: 10
                                },
                                p: { a: 0, k: [494.272, 492.873, 0], ix: 2 },
                                a: { a: 0, k: [526.243, 552.86, 0], ix: 1 },
                                s: { a: 0, k: [64, 64, 100], ix: 6 }
                              },
                              ao: 0,
                              w: 1000,
                              h: 1000,
                              ip: 0,
                              op: 240,
                              st: 0,
                              bm: 0
                            },
                            {
                              ddd: 0,
                              ind: 3,
                              ty: 4,
                              nm: "Shape Layer 4",
                              parent: 6,
                              sr: 1,
                              ks: {
                                o: { a: 0, k: 100, ix: 11 },
                                r: { a: 0, k: 0, ix: 10 },
                                p: { a: 0, k: [-19.161, 40.847, 0], ix: 2 },
                                a: { a: 0, k: [-10.692, 44.978, 0], ix: 1 },
                                s: { a: 0, k: [72.411, 72.411, 100], ix: 6 }
                              },
                              ao: 0,
                              shapes: [
                                {
                                  ty: "gr",
                                  it: [
                                    {
                                      d: 1,
                                      ty: "el",
                                      s: { a: 0, k: [644.596, 644.596], ix: 2 },
                                      p: { a: 0, k: [0, 0], ix: 3 },
                                      nm: "Ellipse Path 1",
                                      mn: "ADBE Vector Shape - Ellipse",
                                      hd: false
                                    },
                                    {
                                      ty: "fl",
                                      c: {
                                        a: 0,
                                        k: [
                                          1, 0.933333333333, 0.866666666667, 1
                                        ],
                                        ix: 4
                                      },
                                      o: { a: 0, k: 100, ix: 5 },
                                      r: 1,
                                      bm: 0,
                                      nm: "Fill 1",
                                      mn: "ADBE Vector Graphic - Fill",
                                      hd: false
                                    },
                                    {
                                      ty: "tr",
                                      p: { a: 0, k: [-8.972, 42.451], ix: 2 },
                                      a: { a: 0, k: [0, 0], ix: 1 },
                                      s: { a: 0, k: [113.699, 113.699], ix: 3 },
                                      r: { a: 0, k: 0, ix: 6 },
                                      o: { a: 0, k: 100, ix: 7 },
                                      sk: { a: 0, k: 0, ix: 4 },
                                      sa: { a: 0, k: 0, ix: 5 },
                                      nm: "Transform"
                                    }
                                  ],
                                  nm: "Ellipse 1",
                                  np: 3,
                                  cix: 2,
                                  bm: 0,
                                  ix: 1,
                                  mn: "ADBE Vector Group",
                                  hd: false
                                }
                              ],
                              ip: 0,
                              op: 240,
                              st: 0,
                              bm: 0
                            },
                            {
                              ddd: 0,
                              ind: 4,
                              ty: 4,
                              nm: "Shape Layer 3",
                              parent: 6,
                              sr: 1,
                              ks: {
                                o: { a: 0, k: 100, ix: 11 },
                                r: { a: 0, k: 0, ix: 10 },
                                p: { a: 0, k: [-27.939, 35.58, 0], ix: 2 },
                                a: { a: 0, k: [-10.692, 44.978, 0], ix: 1 },
                                s: { a: 0, k: [73.438, 73.438, 100], ix: 6 }
                              },
                              ao: 0,
                              shapes: [
                                {
                                  ty: "gr",
                                  it: [
                                    {
                                      d: 1,
                                      ty: "el",
                                      s: { a: 0, k: [644.596, 644.596], ix: 2 },
                                      p: { a: 0, k: [0, 0], ix: 3 },
                                      nm: "Ellipse Path 1",
                                      mn: "ADBE Vector Shape - Ellipse",
                                      hd: false
                                    },
                                    {
                                      ty: "fl",
                                      c: {
                                        a: 0,
                                        k: [
                                          0.911672794118, 0.565675623277,
                                          0.219678527234, 1
                                        ],
                                        ix: 4
                                      },
                                      o: { a: 0, k: 100, ix: 5 },
                                      r: 1,
                                      bm: 0,
                                      nm: "Fill 1",
                                      mn: "ADBE Vector Graphic - Fill",
                                      hd: false
                                    },
                                    {
                                      ty: "tr",
                                      p: { a: 0, k: [-8.972, 42.451], ix: 2 },
                                      a: { a: 0, k: [0, 0], ix: 1 },
                                      s: { a: 0, k: [113.699, 113.699], ix: 3 },
                                      r: { a: 0, k: 0, ix: 6 },
                                      o: { a: 0, k: 100, ix: 7 },
                                      sk: { a: 0, k: 0, ix: 4 },
                                      sa: { a: 0, k: 0, ix: 5 },
                                      nm: "Transform"
                                    }
                                  ],
                                  nm: "Ellipse 1",
                                  np: 3,
                                  cix: 2,
                                  bm: 0,
                                  ix: 1,
                                  mn: "ADBE Vector Group",
                                  hd: false
                                }
                              ],
                              ip: 0,
                              op: 240,
                              st: 0,
                              bm: 0
                            },
                            {
                              ddd: 0,
                              ind: 5,
                              ty: 4,
                              nm: "Shape Layer 2",
                              parent: 6,
                              sr: 1,
                              ks: {
                                o: { a: 0, k: 100, ix: 11 },
                                r: { a: 0, k: 0, ix: 10 },
                                p: { a: 0, k: [-28.312, 35.977, 0], ix: 2 },
                                a: { a: 0, k: [-10.692, 44.978, 0], ix: 1 },
                                s: { a: 0, k: [84.946, 84.946, 100], ix: 6 }
                              },
                              ao: 0,
                              shapes: [
                                {
                                  ty: "gr",
                                  it: [
                                    {
                                      d: 1,
                                      ty: "el",
                                      s: { a: 0, k: [644.596, 644.596], ix: 2 },
                                      p: { a: 0, k: [0, 0], ix: 3 },
                                      nm: "Ellipse Path 1",
                                      mn: "ADBE Vector Shape - Ellipse",
                                      hd: false
                                    },
                                    {
                                      ty: "fl",
                                      c: {
                                        a: 0,
                                        k: [
                                          1, 0.692156862745, 0.352159926471, 1
                                        ],
                                        ix: 4
                                      },
                                      o: { a: 0, k: 100, ix: 5 },
                                      r: 1,
                                      bm: 0,
                                      nm: "Fill 1",
                                      mn: "ADBE Vector Graphic - Fill",
                                      hd: false
                                    },
                                    {
                                      ty: "tr",
                                      p: { a: 0, k: [-8.972, 42.451], ix: 2 },
                                      a: { a: 0, k: [0, 0], ix: 1 },
                                      s: { a: 0, k: [113.699, 113.699], ix: 3 },
                                      r: { a: 0, k: 0, ix: 6 },
                                      o: { a: 0, k: 100, ix: 7 },
                                      sk: { a: 0, k: 0, ix: 4 },
                                      sa: { a: 0, k: 0, ix: 5 },
                                      nm: "Transform"
                                    }
                                  ],
                                  nm: "Ellipse 1",
                                  np: 3,
                                  cix: 2,
                                  bm: 0,
                                  ix: 1,
                                  mn: "ADBE Vector Group",
                                  hd: false
                                }
                              ],
                              ip: 0,
                              op: 240,
                              st: 0,
                              bm: 0
                            },
                            {
                              ddd: 0,
                              ind: 6,
                              ty: 4,
                              nm: "Shape Layer 1",
                              sr: 1,
                              ks: {
                                o: { a: 0, k: 100, ix: 11 },
                                r: { a: 0, k: 0, ix: 10 },
                                p: { a: 0, k: [506.68, 499.573, 0], ix: 2 },
                                a: { a: 0, k: [-10.692, 44.978, 0], ix: 1 },
                                s: { a: 0, k: [113.919, 113.919, 100], ix: 6 }
                              },
                              ao: 0,
                              shapes: [
                                {
                                  ty: "gr",
                                  it: [
                                    {
                                      d: 1,
                                      ty: "el",
                                      s: { a: 0, k: [644.596, 644.596], ix: 2 },
                                      p: { a: 0, k: [0, 0], ix: 3 },
                                      nm: "Ellipse Path 1",
                                      mn: "ADBE Vector Shape - Ellipse",
                                      hd: false
                                    },
                                    {
                                      ty: "fl",
                                      c: {
                                        a: 0,
                                        k: [
                                          0.869990808824, 0.46238564884,
                                          0.016005818984, 1
                                        ],
                                        ix: 4
                                      },
                                      o: { a: 0, k: 100, ix: 5 },
                                      r: 1,
                                      bm: 0,
                                      nm: "Fill 1",
                                      mn: "ADBE Vector Graphic - Fill",
                                      hd: false
                                    },
                                    {
                                      ty: "tr",
                                      p: { a: 0, k: [-10.692, 44.978], ix: 2 },
                                      a: { a: 0, k: [0, 0], ix: 1 },
                                      s: { a: 0, k: [100, 100], ix: 3 },
                                      r: { a: 0, k: 0, ix: 6 },
                                      o: { a: 0, k: 100, ix: 7 },
                                      sk: { a: 0, k: 0, ix: 4 },
                                      sa: { a: 0, k: 0, ix: 5 },
                                      nm: "Transform"
                                    }
                                  ],
                                  nm: "Ellipse 1",
                                  np: 3,
                                  cix: 2,
                                  bm: 0,
                                  ix: 1,
                                  mn: "ADBE Vector Group",
                                  hd: false
                                }
                              ],
                              ip: 0,
                              op: 240,
                              st: 0,
                              bm: 0
                            }
                          ],
                          markers: []
                        }}
                        className={classNames("__wab_instance", sty.lottie)}
                      />
                    )}
                  </DataCtxReader__>
                }
                method={"POST"}
                noLayout={false}
                previewSpinner={false}
                queryKey={(() => {
                  try {
                    return undefined;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return undefined;
                    }
                    throw e;
                  }
                })()}
                url={"https://api.openai.com/v1/chat/completions"}
              >
                <DataCtxReader__>
                  {$ctx => (
                    <React.Fragment>
                      <Reveal
                        data-plasmic-name={"reveal"}
                        data-plasmic-override={overrides.reveal}
                        className={classNames("__wab_instance", sty.reveal)}
                        direction={"up"}
                        effect={"slide"}
                        triggerOnce={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xoiot
                          )}
                        >
                          <div
                            className={projectcss.__wab_expr_html_text}
                            dangerouslySetInnerHTML={{
                              __html: (() => {
                                try {
                                  return $ctx.openAIResponse.choices[0].message
                                    .content;
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "Enter some text";
                                  }
                                  throw e;
                                }
                              })()
                            }}
                          />
                        </div>
                      </Reveal>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___0S0G9
                        )}
                      >
                        <div
                          className={projectcss.__wab_expr_html_text}
                          dangerouslySetInnerHTML={{
                            __html: (() => {
                              try {
                                return undefined;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "Enter some text";
                                }
                                throw e;
                              }
                            })()
                          }}
                        />
                      </div>
                    </React.Fragment>
                  )}
                </DataCtxReader__>
              </DataFetcher>
            ) : null}
          </Stack__>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "section",
    "h1",
    "textInput",
    "button",
    "openAiCall",
    "reveal",
    "lottie"
  ],
  section: [
    "section",
    "h1",
    "textInput",
    "button",
    "openAiCall",
    "reveal",
    "lottie"
  ],
  h1: ["h1"],
  textInput: ["textInput"],
  button: ["button"],
  openAiCall: ["openAiCall", "reveal", "lottie"],
  reveal: ["reveal"],
  lottie: ["lottie"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  section: "section";
  h1: "h1";
  textInput: typeof TextInput;
  button: typeof Button;
  openAiCall: typeof DataFetcher;
  reveal: typeof Reveal;
  lottie: typeof LottieWrapper;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    section: makeNodeComponent("section"),
    h1: makeNodeComponent("h1"),
    textInput: makeNodeComponent("textInput"),
    button: makeNodeComponent("button"),
    openAiCall: makeNodeComponent("openAiCall"),
    reveal: makeNodeComponent("reveal"),
    lottie: makeNodeComponent("lottie"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "What Can I Make? Quick Recipes Ideas ",
      description:
        "Not sure what to make tonight? Get some inspiration using the ingredients you have.",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
